# frozen_string_literal: true

require 'nokogiri'
require 'json'
module Snackhack2
  class WordPress
    attr_accessor :save_file, :site

    def initialize(save_file: true)
      @site = site
      @save_file = save_file
    end

    def run
      wp_login
      yoast_seo
      users
      wp_content_uploads
      all_in_one_seo
      wp_log
    end

    def file_site
      @site = @site.gsub('https://', '')
    end

    def users
      found_users = ''
      begin
        users = Snackhack2.get(File.join(@site, 'wp-json', 'wp', 'v2', 'users')).body
        json = JSON.parse(users)
        json.each do |k|
          found_users += "#{k['name']}\n"
        end
      rescue StandardError
        puts "[+] users not found\n\n\n"
      end

      return if found_users.empty?

      if @save_file
        Snackhack2.file_save(@site, 'users', found_users)
      else
        puts found_users
      end
    end

    def wp_content_uploads
      s = Snackhack2.get(File.join(@site, '/wp-content/uploads/'))
      return unless s.code == 200
      return unless s.body.include?('Index of')

      puts "[+] #{File.join(@site, '/wp-content/uploads/')} is valid...\n\n\n"
    end

    def wp_login
      # detects if the site is using wordpress
      percent = 0
      ## todo: maybe add Bayes Theorem to detect wp
      wp = ['wp-includes', 'wp-admin', 'Powered by WordPress', 'wp-login.php', 'yoast.com/wordpress/plugins/seo/',
            'wordpress-login-url.jpg', 'wp-content/themes/', 'wp-json']
      login = Snackhack2.get(File.join(@site, 'wp-login.php'))
      if login.code == 200
        wp.each do |path|
          percent += 10 if login.body.include?(path)
        end
      end
      login2 = Snackhack2.get(@site.to_s)
      wp.each do |path|
        percent += 10 if login2.body.include?(path)
      end
      puts "Wordpress Points: #{percent}"
    end

    def yoast_seo(print_version: false)
      # checks to see if the wordpress site
      # uses the yoast seo plugin
      ys = Snackhack2.get(@site)
      if ys.code.to_i.eql?(200)
        if ys.body.match?("Yoast")
          v = ys.body.scan(/This site is optimized with the Yoast SEO plugin\sv\d\d\.\d/).join(" ")
          # makes sure the word 'plugin' is in the 'v' string
          if v.include?("plugin") 
            # gets the version
            version = v.split("plugin")[1].strip
          end
        end
      end
      unless print_version
        return version
      else
        puts "Yoast Seo is running version: #{version}"
      end
    end

    def find_plugins(print_version: true)
      found_versions = {}
      alios = Snackhack2.get(@site)
      if alios.code.eql?(200)
        data = {"Yoast SEO plugin " => 'Yoast SEO plugin v\d\d\.\d',
                "MonsterInsights plugin" => 'MonsterInsights plugin v\d\d\.\d\.\d',
                "All in One SEO" => 'All in One SEO \d\.\d\.\d\.\d',
                "Site Kit by Google" => 'Site Kit by Google \d\.\d\d\d\.\d',
                 "Google Analytics by ExactMetrics plugin" => 'Google Analytics by ExactMetrics plugin v\d\.\d\d\.\d', "HubSpot WordPress plugin" => 'HubSpot WordPress plugin v\d\d\.\d\.\d\d', "Simple Social Buttons" => 'Simple Social Buttons \d\.2\.0', 
                 "Powered by Slider Revolution" => 'Powered by Slider Revolution \d\.\d\.\d\d', "Generated By Events-Calendar - Version:" => 'Generated By Events-Calendar - Version: \d\.\d\.\d',
                 "Open Graph and Twitter Card Tags" => 'Open Graph and Twitter Card Tags \d\.\d\.\d',
                 "Google Analytics Tracking by Google Analyticator" => 'Google Analytics Tracking by Google Analyticator \d\.\d\.\d', "REVOLUTION SLIDER" => 'REVOLUTION SLIDER \d\.\d\.\d',
                 "Generated By sidebarTabs" => 'Generated By sidebarTabs \d\.\d',\
                 "Yoast WordPress SEO plugin" => 'Yoast WordPress SEO plugin v\d\.\d\.\d',
                 "Yoast SEO Premium plugin" => 'Yoast SEO Premium plugin v\d\d\.\d \(Yoast SEO v27\.1\.1\)',
                 "Google Analytics by MonsterInsights plugin" => 'Google Analytics by MonsterInsights plugin v\d\d\.\d\.\d',
                 "All in One SEO (AIOSEO\)" => 'All in One SEO \(AIOSEO\) \d\.\d\.\d',
                 "EduBlock PRO" => 'EduBlock PRO \d\.\d\.\d',
                 "WPZOOM Framework" => 'WPZOOM Framework \d\.0\.\d',
                 "WPML" => 'WPML ver:\d\.\d\.\d',
                 "Redux" => 'Redux \d\.\d\.\d',
                 "WordPress Download Manager"=> 'WordPress Download Manager \d\.\d\.\d\d',
                 "WP Rocket" => 'WP Rocket \d\.\d\d\.\d',
                 "WooCommerce" => 'WooCommerce \d\d\.\d\.\d',
                 "Yoast SEO plugin" => 'Yoast SEO plugin v\d\.\d',
                 "Divi" => 'Divi v\.\d\.\d\d\.\d',
                 "WordPress" => 'WordPress \d\.\d\.\d',
                 "Newtek ChildTheme Base for Divi " => 'Newtek ChildTheme Base for Divi v\.\d\.\d',
                 "Presence" => 'Presence \d\.\d\.\d\d',
                 "WPZOOM Framework" => 'WPZOOM Framework \d\.\d\.\d'}
        data.each do |name, regex|
          version = alios.body.scan(/#{regex}/)

          unless version.empty?
            found_versions[name] = version.shift.gsub(name, "").strip
          end
        end
      end
      unless print_version 
        return found_versions
      else
        found_versions.each do |name, version|
          puts "#{name}: #{version}" 
        end
      end
    end
    def wp_log
      wplog_score = 0
      wp = ['\wp-content\plugins', 'PHP Notice', 'wp-cron.php', '/var/www/html', 'Yoast\WP\SEO', 'wordpress-seo']
      log = Snackhack2.get(File.join(@site, '/wp-content/debug.log'))
      if log.code == 200
        puts "[+] #{File.join(@site, '/wp-content/debug.log')} is giving status 200. Now double checking...\n\n\n"
        wp.each do |e|
          wplog_score += 10 if log.body.include?(e)
        end
      end
      puts "WordPress Log score: #{wplog_score}...\n\n\n"
    end

    def wp_plugin
      wp_plugin_score = 0
      # text in which it will search for
      wp = ['Index of', 'Name', 'Last modified', 'Size', 'Parent Directory', '/wp-content/plugins']
      plug = Snackhack2.get(File.join(@site, '/wp-content/plugins/'))
      if plug.code == 200
        puts "[+] Looks like #{File.join(@site,
                                         '/wp-content/plugins/')} is giving status 200. Checking to make sure...\n\n\n"
        wp.each do |e|
          wp_plugin_score += 10 if plug.body.include?(e)
        end
      end
      puts "[+] WordPress Plugin Score: #{wp_plugin_score}"
    end
  end
end
